import Config

# Include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :epochtalk_server, EpochtalkServerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: EpochtalkServer.Finch

if File.exists?("config/prod.secret.exs") do
  import_config "prod.secret.exs"
end
