name: Build-ECR

on:
  push:
    branches:
      - master
      - github-actions

jobs:
  build_job:
    name: Build
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6.1
    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        ref: ${{ github.event.client_payload.branch }}
    # - name: Build
    #   run: docker build --tag epochtalk_server .
  release_job:
    name: Release
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          dry_run: true
          semantic_version: 19.0.5
          branches: |
            [
              'master',
              'github-actions'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
