name: CI test and build

on:
  push:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.14.0']
        otp: ['25.0.4']
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.1
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1.14.0
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve cached dependencies
        uses: actions/cache@v3.0.11
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
  static-code-analysis:
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.14.0']
        otp: ['25.0.4']
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1.14.0
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve cached dependencies
        uses: actions/cache@v3.0.11
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - run: mix format --check-formatted
      - run: mix credo || ret=$?; if [ $ret != 2 ]; then exit $ret; fi
      - run: mix dialyzer --no-check --ignore-exit-status
  test_job:
    needs: dependencies
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.14.0']
        otp: ['25.0.4']
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: epochtalk_server_test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        ports:
          - 6379:6379
        image: redis:7.0.4
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.1
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1.14.0
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve cached dependencies
        uses: actions/cache@v3.0.11
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Run tests
        run: mix test
  # pre_release_job:
  #   needs: test_job
  #   name: Pre-Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.1.0
  #     - name: Semantic Release
  #       uses: cycjimmy/semantic-release-action@v3.0.0
  #       with:
  #         dry_run: true
  #         semantic_version: 19.0.5
  #         branches: |
  #           [
  #             'github-actions'
  #           ]
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_job:
    needs: test_job
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          semantic_version: 19.0.5
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
jobs:
  generateDocs:
    name: Generate project documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1.14.0
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Build docs
        uses: lee-dohm/generate-elixir-docs@v1.0.1
      - name: Publish to Pages
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
