name: Build-ECR

on:
  push:
    branches:
      - master
      - github-actions

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.1
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.event.client_payload.branch }}
  test_job:
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: epochtalk_server
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7.0.4
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    needs: build_job
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: false
          load: true
          tags: epochtalk/epochtalk_server:latest
      - name: Run tests in docker container
        run: docker run --rm -e MIX_ENV=test -e DATABASE_USER=$DATABASE_USER -e DATABASE_PASSWORD=$DATABASE_PASSWORD -e DATABASE_NAME=$DATABASE_NAME -e DATABASE_HOST=$DATABASE_HOST -e REDIS_HOST=$REDIS_HOST -e SECRET_KEY_BASE=$SECRET_KEY_BASE -e GUARDIAN_SECRET_KEY=$GUARDIAN_SECRET_KEY epochtalk/epochtalk_server mix test
        env:
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: epochtalk_server
          DATABASE_HOST: postgres
          REDIS_HOST: redis
          SECRET_KEY_BASE: ${{ secrets.TEST_SECRET_KEY_BASE }}
          GUARDIAN_SECRET_KEY: ${{ secrets.TEST_GUARDIAN_SECRET_KEY }}
  pre_release_job:
    needs: test_job
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          dry_run: true
          semantic_version: 19.0.5
          branches: |
            [
              'github-actions'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_job:
    needs: test_job
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          semantic_version: 19.0.5
          branches: |
            [
              'master'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
